name: Testing
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  building:
    runs-on: ubuntu-latest
    steps:
      - name: Begin building
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Use cached node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test:coverage

      - name: Run build
        run: yarn build
